---
ID: "4dd3b143-630e-429e-b44c-0bd02fea869e"
Parent: "f6903826-6877-492e-a546-0f233a191db6"
Template: "f6903826-6877-492e-a546-0f233a191db6"
Path: /sitecore/templates/Project/ContosoCorp/App Route/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240106T012326Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
