---
ID: "0e2e6ac8-ef3a-43c4-9786-d6173fd2b28a"
Parent: "dceb901d-4ec8-4a2d-877d-5524da095b1f"
Template: "dceb901d-4ec8-4a2d-877d-5524da095b1f"
Path: /sitecore/templates/Project/ContosoCorp/Partial Design Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {DCEB901D-4EC8-4A2D-877D-5524DA095B1F}
    {FD2059FD-6043-4DFE-8C04-E2437CE87634}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240106T012326Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
