---
ID: "fe2cc640-7906-4bf7-b873-f4d41901ddd5"
Parent: "a3e74e37-9853-4860-bebc-374bcb1ad9cb"
Template: "d2923fee-da4e-49be-830c-e27764dfa269"
Path: /sitecore/content/ContosoCorp/CorporateSite/Settings/Enums/Background Colors/default
DB: master
SharedFields:
- ID: "f917c951-1f75-4d62-b14a-bc6888d7eeca"
  Hint: Value
  Value: default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240114T055446Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
